<a href="https://colab.research.google.com/github/amritesh-21/amritesh18cse076/blob/main/Assignment_1%262.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment-1

---







#1

In [ ]:
num_list = [21, 11, 19, 3,11,5]
# FInd sum of the numbers
num_sum = sum(num_list)
#divide the sum with length of the list
mean = num_sum / len(num_list)
print(num_list)
print("Mean of the above list of numbers is: ",mean)


[21, 11, 19, 3, 11, 5]
Mean of the above list of numbers is:  11.666666666666666


In [ ]:
num_list = [21, 11, 19, 3,11,5]
# FInd sum of the numbers
num_sum = sum(num_list)
#divide the sum with length of the list
mean = num_sum / len(num_list)
print(num_list)
print("Mean of the above list of numbers is: " + str(round(mean,2)))

[21, 11, 19, 3, 11, 5]
Mean of the above list of numbers is: 11.67


In [ ]:
import collections
# list of elements to calculate mode
num_list = [21, 13, 19, 13,19,13]
# Print the list
print(num_list)
# calculate the frequency of each item
data = collections.Counter(num_list)
data_list = dict(data)
# Print the items with frequency
print(data_list)
# Find the highest frequency
max_value = max(list(data.values()))
mode_val = [num for num, freq in data_list.items() if freq == max_value]
if len(mode_val) == len(num_list):
   print("No mode in the list")
else:
   print("The Mode of the list is : " + ', '.join(map(str, mode_val)))

[21, 13, 19, 13, 19, 13]
{21: 1, 13: 3, 19: 2}
The Mode of the list is : 13


#2

In [ ]:
def variance(data):
     # Number of observations
     n = len(data)
     # Mean of the data
     mean = sum(data) / n
     # Square deviations
     deviations = [(x - mean) ** 2 for x in data]
     # Variance
     variance = sum(deviations) / n
     return variance
variance([4, 8, 6, 5, 3, 2, 8, 9, 2, 5])

5.76

In [ ]:
import math
def variance(data):
     n = len(data)
     mean = sum(data) / n
     deviations = [(x - mean) ** 2 for x in data]
     variance = sum(deviations) / n
     return variance
def stdev(data):
     var = variance(data)
     std_dev = math.sqrt(var)
     return std_dev

stdev([4, 8, 6, 5, 3, 2, 8, 9, 2, 5])

2.4

#3

In [ ]:
#List 
L = [1, "a" , "string" , 1+2] 
print(L) 
L.append(6) 
print (L) 
L.pop() 
print(L) 
print(L[1])

#Tuple
tup = (1, "a", "string", 1+2) 
print(tup) 
print(tup[1]) 

#String
s = "Hello World"
for i in s : 
    print (i)

#Dictionary
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
print(dict1)

[1, 'a', 'string', 3]
[1, 'a', 'string', 3, 6]
[1, 'a', 'string', 3]
a
(1, 'a', 'string', 3)
a
H
e
l
l
o
 
W
o
r
l
d
{'Ten': 10, 'Twenty': 20, 'Thirty': 30}


#Assignment - 2

In [10]:
import pandas as pd

In [15]:
from google.colab import files
uploaded=files.upload()

Saving Pokemon.csv to Pokemon.csv


In [16]:
import io

In [17]:
df=pd.read_csv(io.BytesIO(uploaded["Pokemon.csv"]))

In [18]:
df.head()

#                   Name Type 1  ... Speed  Generation  Legendary
0  1              Bulbasaur  Grass  ...    45           1      False
1  2                Ivysaur  Grass  ...    60           1      False
2  3               Venusaur  Grass  ...    80           1      False
3  3  VenusaurMega Venusaur  Grass  ...    80           1      False
4  4             Charmander   Fire  ...    65           1      False

[5 rows x 13 columns]

In [19]:
df.tail()

#                 Name   Type 1  ... Speed  Generation  Legendary
795  719              Diancie     Rock  ...    50           6       True
796  719  DiancieMega Diancie     Rock  ...   110           6       True
797  720  HoopaHoopa Confined  Psychic  ...    70           6       True
798  720   HoopaHoopa Unbound  Psychic  ...    80           6       True
799  721            Volcanion     Fire  ...    70           6       True

[5 rows x 13 columns]

#2 Practice 10 python programs using numpy libraries.

In [20]:
import numpy as np
x = np.eye(5,dtype=int)
print("x =\n",x)

x =
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [36]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [21]:
import numpy as np
a = [[1, 2], [3, 4]]
x = np.array(a)
print("list to array:\n",x)
a2 = x.tolist()
print("array to list:\n",a2)
print(a == a2)

list to array:
 [[1 2]
 [3 4]]
array to list:
 [[1, 2], [3, 4]]
True


In [37]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [26]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.32177077 0.40103823 0.57253732 0.79354348 0.04586433]
 [0.8736775  0.10889712 0.51296176 0.0732783  0.47162935]
 [0.04040477 0.54161871 0.20379158 0.09022012 0.52720768]
 [0.99577293 0.59046954 0.69849459 0.32943152 0.54514085]
 [0.23153077 0.65833182 0.00811373 0.21087551 0.06975786]]
Minimum and Maximum Values:
0.008113728716270807 0.9957729327166129


In [23]:
import numpy as np
nums =  np.random.rand(15)
print("Original array:")
print(nums)
print("\nSorted first 5 elements:")
print(nums[np.argpartition(nums,range(8))])

Original array:
[0.94434521 0.58915081 0.92100399 0.84151431 0.50748722 0.83397201
 0.30676142 0.21330236 0.02012902 0.17546695 0.34683304 0.18919984
 0.72691119 0.37950881 0.31827639]

Sorted first 5 elements:
[0.02012902 0.17546695 0.18919984 0.21330236 0.30676142 0.31827639
 0.34683304 0.37950881 0.94434521 0.58915081 0.50748722 0.92100399
 0.72691119 0.84151431 0.83397201]


In [27]:
x = np.array([[1,2,3], [4,5,6]])
print("Original array: ")
print(x)
print("Cumulative sum of the elements along a given axis:")
r = np.cumsum(x)
print(r)
print("\nSum over rows for each of the 3 columns:")
r = np.cumsum(x,axis=0) 
print(r)
print("\nSum over columns for each of the 2 rows:")
r = np.cumsum(x,axis=1) 
print(r)

Original array: 
[[1 2 3]
 [4 5 6]]
Cumulative sum of the elements along a given axis:
[ 1  3  6 10 15 21]

Sum over rows for each of the 3 columns:
[[1 2 3]
 [5 7 9]]

Sum over columns for each of the 2 rows:
[[ 1  3  6]
 [ 4  9 15]]


In [28]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-11-20
Today:  2020-11-21
Tomorrow:  2020-11-22


In [29]:
import numpy as np
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
stripped = np.char.strip(x)
print("\nRemove the leading and trailing whitespaces: ", stripped)

Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the leading and trailing whitespaces:  ['python exercises' 'PHP' 'java' 'C++']


#3 Practice 10 python methos using pandas libraries.

In [40]:
#1.Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [42]:
#2.Write a Pandas program to iterate over rows in a DataFrame.
import pandas as pd
import numpy as np
exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]
df = pd.DataFrame(exam_data)
for index, row in df.iterrows():
    print(row['name'], row['score'])

Anastasia 12.5
Dima 9.0
Katherine 16.5


In [41]:
#3.Write a Pandas program to start index with different value rather than 0 in a given DataFrame.
import pandas as pd
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_of_birth': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'weight': [35, 37, 33, 30, 31, 32]})
     
print("Original DataFrame:")
print(df)
print("\nDefault Index Range:")
print(df.index)
df.index += 10 
print("\nNew Index Range:")
print(df.index)
print("\nDataFrame with new index:")
print(df)

Original DataFrame:
  school_code class            name date_of_birth  weight
0        s001     V  Alberto Franco    15/05/2002      35
1        s002     V    Gino Mcneill    17/05/2002      37
2        s003    VI     Ryan Parkes    16/02/1999      33
3        s001    VI    Eesha Hinton    25/09/1998      30
4        s002     V    Gino Mcneill    11/05/2002      31
5        s004    VI    David Parkes    15/09/1997      32

Default Index Range:
RangeIndex(start=0, stop=6, step=1)

New Index Range:
RangeIndex(start=10, stop=16, step=1)

DataFrame with new index:
   school_code class            name date_of_birth  weight
10        s001     V  Alberto Franco    15/05/2002      35
11        s002     V    Gino Mcneill    17/05/2002      37
12        s003    VI     Ryan Parkes    16/02/1999      33
13        s001    VI    Eesha Hinton    25/09/1998      30
14        s002     V    Gino Mcneill    11/05/2002      31
15        s004    VI    David Parkes    15/09/1997      32


In [43]:
#4.Write a Pandas program to extract only phone number from the specified column of a given DataFrame.
import pandas as pd
import re as re
pd.set_option('display.max_columns', 10)
df = pd.DataFrame({
    'company_code': ['c0001','c0002','c0003', 'c0003', 'c0004'],
    'company_phone_no': ['Company1-Phone no. 4695168357','Company2-Phone no. 8088729013','Company3-Phone no. 6204658086', 'Company4-Phone no. 5159530096', 'Company5-Phone no. 9037952371']
    })
print("Original DataFrame:")
print(df)
def find_phone_number(text):
    ph_no = re.findall(r"\b\d{10}\b",text)
    return "".join(ph_no)
df['number']=df['company_phone_no'].apply(lambda x: find_phone_number(x))
print("\Extracting numbers from dataframe columns:")
print(df)

Original DataFrame:
  company_code               company_phone_no
0        c0001  Company1-Phone no. 4695168357
1        c0002  Company2-Phone no. 8088729013
2        c0003  Company3-Phone no. 6204658086
3        c0003  Company4-Phone no. 5159530096
4        c0004  Company5-Phone no. 9037952371
\Extracting numbers from dataframe columns:
  company_code               company_phone_no      number
0        c0001  Company1-Phone no. 4695168357  4695168357
1        c0002  Company2-Phone no. 8088729013  8088729013
2        c0003  Company3-Phone no. 6204658086  6204658086
3        c0003  Company4-Phone no. 5159530096  5159530096
4        c0004  Company5-Phone no. 9037952371  9037952371


In [44]:
#5.Write a Pandas program to Combine two DataFrame objects by filling null values in one DataFrame with non-null values from other DataFrame.
import pandas as pd
df1 = pd.DataFrame({'A': [None, 0, None], 'B': [3, 4, 5]})
df2 = pd.DataFrame({'A': [1, 1, 3], 'B': [3, None, 3]})
df1.combine_first(df2)
print("Original DataFrames:")
print(df1)
print("--------------------")
print(df2)
print("\nMerge two dataframes with different columns:")
result = df1.combine_first(df2)
print(result)

Original DataFrames:
     A  B
0  NaN  3
1  0.0  4
2  NaN  5
--------------------
   A    B
0  1  3.0
1  1  NaN
2  3  3.0

Merge two dataframes with different columns:
     A  B
0  1.0  3
1  0.0  4
2  3.0  5


In [45]:
#6.Write a Pandas program to create
#a) Datetime object for Jan 15 2012.
#b) Specific date and time of 9:20 pm.
#c) Local date and time.
#d) A date without time.
#e) Current date.
#f) Time from a datetime.
#g) Current local time.
import datetime
from datetime import datetime
print("Datetime object for Jan 11 2012:")
print(datetime(2012, 1, 11))
print("\nSpecific date and time of 9:20 pm") 
print(datetime(2011, 1, 11, 21, 20))
print("\nLocal date and time:")
print(datetime.now())
print("\nA date without time: ")
print(datetime.date(datetime(2012, 5, 22)))
print("\nCurrent date:")
print(datetime.now().date())
print("\nTime from a datetime:")
print(datetime.time(datetime(2012, 12, 15, 18, 12)))
print("\nCurrent local time:") 
print(datetime.now().time())

Datetime object for Jan 11 2012:
2012-01-11 00:00:00

Specific date and time of 9:20 pm
2011-01-11 21:20:00

Local date and time:
2020-11-21 15:13:36.346846

A date without time: 
2012-05-22

Current date:
2020-11-21

Time from a datetime:
18:12:00

Current local time:
15:13:36.348313


In [46]:
#7.Write a Pandas program to find out the alcohol consumption details in the year '1986' or '1989' where WHO region is 'Americas' or 'Europe' from the world alcohol consumption dataset.
import pandas as pd
url = "https://raw.githubusercontent.com/Akash2oc98/18cse037-gietu_DMDW_lab-work/main/world_alcohol.csv"
w_a_con =pd.read_csv(url)
print("World alcohol consumption sample data:")
print(w_a_con.head())
print("\nThe world alcohol consumption details in the year ‘1986’ or ‘1989’ where  WHO region is ‘Americas’  or 'Europe':")
print(w_a_con[((w_a_con['Year']==1985) | (w_a_con['Year']==1989)) & ((w_a_con['WHO region']=='Americas') | (w_a_con['WHO region']=='Europe'))].head(10))

World alcohol consumption sample data:
   Year       WHO region                Country Beverage Types  Display Value
0  1986  Western Pacific               Viet Nam           Wine           0.00
1  1986         Americas                Uruguay          Other           0.50
2  1985           Africa           Cte d'Ivoire           Wine           1.62
3  1986         Americas               Colombia           Beer           4.27
4  1987         Americas  Saint Kitts and Nevis           Beer           1.98

The world alcohol consumption details in the year ‘1986’ or ‘1989’ where  WHO region is ‘Americas’  or 'Europe':
    Year WHO region                                            Country  \
11  1989   Americas                                          Guatemala   
21  1989   Americas                                         Costa Rica   
26  1985     Europe  United Kingdom of Great Britain and Northern I...   
35  1985   Americas                              Saint Kitts and Nevis   
44  1985 

In [47]:
#8
"""Write a Pandas program to split the following dataset using group by on 'salesman_id' and find the first order date for each group.

Test Data:

    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3002         5002
1    70009     270.65  2012-09-10         3001         5003
2    70002      65.26  2012-10-05         3001         5001
3    70004     110.50  2012-08-17         3003         5003
4    70007     948.50  2012-09-10         3002         5002
5    70005    2400.60  2012-07-27         3002         5001
6    70008    5760.00  2012-09-10         3001         5001
7    70010    1983.43  2012-10-10         3004         5003
8    70003    2480.40  2012-10-10         3003         5003
9    70012     250.45  2012-06-27         3002         5002
10   70011      75.29  2012-08-17         3003         5003
11   70013    3045.60  2012-04-25         3001         5001"""
import pandas as pd
pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
df = pd.DataFrame({
'ord_no':[70001,70009,70002,70004,70007,70005,70008,70010,70003,70012,70011,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': ['2012-10-05','2012-09-10','2012-10-05','2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3005,3001,3002,3009,3005,3007,3002,3004,3009,3008,3003,3002],
'salesman_id': [5002,5005,5001,5003,5002,5001,5001,5004,5003,5002,5004,5001]})
print("Original Orders DataFrame:")
print(df)
print("\nGroupby to find first order date for each group(salesman_id):")
result = df.groupby('salesman_id')['ord_date'].min()
print(result)

Original Orders DataFrame:
    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3005         5002
1    70009     270.65  2012-09-10         3001         5005
2    70002      65.26  2012-10-05         3002         5001
3    70004     110.50  2012-08-17         3009         5003
4    70007     948.50  2012-09-10         3005         5002
5    70005    2400.60  2012-07-27         3007         5001
6    70008    5760.00  2012-09-10         3002         5001
7    70010    1983.43  2012-10-10         3004         5004
8    70003    2480.40  2012-10-10         3009         5003
9    70012     250.45  2012-06-27         3008         5002
10   70011      75.29  2012-08-17         3003         5004
11   70013    3045.60  2012-04-25         3002         5001

Groupby to find first order date for each group(salesman_id):
salesman_id
5001    2012-04-25
5002    2012-06-27
5003    2012-08-17
5004    2012-08-17
5005    2012-09-10
Name: ord_date, dtype: 

In [48]:
#9
"""Write a Pandas program to find and replace the missing values in a given DataFrame which do not have any valuable information.

Example:
Missing values: ?, --
Replace those values with NaN

Test Data:

   ord_no purch_amt    ord_date customer_id salesman_id
0   70001     150.5           ?        3002        5002
1     NaN    270.65  2012-09-10        3001        5003
2   70002     65.26         NaN        3001           ?
3   70004     110.5  2012-08-17        3003        5001
4     NaN     948.5  2012-09-10        3002         NaN
5   70005    2400.6  2012-07-27        3001        5002
6      --      5760  2012-09-10        3001        5001
7   70010         ?  2012-10-10        3004           ?
8   70003     12.43  2012-10-10          --        5003
9   70012    2480.4  2012-06-27        3002        5002
10    NaN    250.45  2012-08-17        3001        5003
11  70013    3045.6  2012-04-25        3001          --   """
import numpy as np
pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
df = pd.DataFrame({
'ord_no':[70001,np.nan,70002,70004,np.nan,70005,"--",70010,70003,70012,np.nan,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,"?",12.43,2480.4,250.45, 3045.6],
'ord_date': ['?','2012-09-10',np.nan,'2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3002,3001,3001,3003,3002,3001,3001,3004,"--",3002,3001,3001],
'salesman_id':[5002,5003,"?",5001,np.nan,5002,5001,"?",5003,5002,5003,"--"]})
print("Original Orders DataFrame:")
print(df)
print("\nReplace the missing values with NaN:")
result = df.replace({"?": np.nan, "--": np.nan})
print(result)

Original Orders DataFrame:
   ord_no purch_amt    ord_date customer_id salesman_id
0   70001     150.5           ?        3002        5002
1     NaN    270.65  2012-09-10        3001        5003
2   70002     65.26         NaN        3001           ?
3   70004     110.5  2012-08-17        3003        5001
4     NaN     948.5  2012-09-10        3002         NaN
5   70005    2400.6  2012-07-27        3001        5002
6      --      5760  2012-09-10        3001        5001
7   70010         ?  2012-10-10        3004           ?
8   70003     12.43  2012-10-10          --        5003
9   70012    2480.4  2012-06-27        3002        5002
10    NaN    250.45  2012-08-17        3001        5003
11  70013    3045.6  2012-04-25        3001          --

Replace the missing values with NaN:
     ord_no  purch_amt    ord_date  customer_id  salesman_id
0   70001.0     150.50         NaN       3002.0       5002.0
1       NaN     270.65  2012-09-10       3001.0       5003.0
2   70002.0      65.26  

In [49]:
#10.Create a dataframe of ten rows, four columns with random values. Write a Pandas program to display bar charts in dataframe on specified columns.
import pandas as pd
import numpy as np
np.random.seed(24)
df = pd.DataFrame({'A': np.linspace(1, 10, 10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10, 4), columns=list('BCDE'))],
               axis=1)
df.iloc[0, 2] = np.nan
df.iloc[3, 3] = np.nan
df.iloc[4, 1] = np.nan
df.iloc[9, 4] = np.nan
print("Original array:")
print(df)
print("\nBar charts in dataframe:")
df.style.bar(subset=['B', 'C'], color='#d65f5f')

Original array:
      A         B         C         D         E
0   1.0  1.329212       NaN -0.316280 -0.990810
1   2.0 -1.070816 -1.438713  0.564417  0.295722
2   3.0 -1.626404  0.219565  0.678805  1.889273
3   4.0  0.961538  0.104011       NaN  0.850229
4   5.0       NaN  1.057737  0.165562  0.515018
5   6.0 -1.336936  0.562861  1.392855 -0.063328
6   7.0  0.121668  1.207603 -0.002040  1.627796
7   8.0  0.354493  1.037528 -0.385684  0.519818
8   9.0  1.686583 -1.325963  1.428984 -2.089354
9  10.0 -0.129820  0.631523 -0.586538       NaN

Bar charts in dataframe:
